### ISSUE TITLE
Milestone 03

### ISSUE THREAD

**Issue by DLT360-Guilherme** [DLT360/043_Fund12#3]
- [ ] Requirements Specification (Final Version)
- [ ] Solution Specification (Final Version)
- [ ] Business Model Specification
- [ ] Website
- [ ] Pitch-Deck and Pitch-Video
