### ISSUE TITLE
Milestone 1 Evidence

### ISSUE THREAD

**Issue by DLT360-Guilherme** [DLT360/043_Fund12#8]
### Demonstrating and explaining the MIRO Board with the detailed definition of the deliverables of this project by showing the content-structure of the folwing deliverables:
- [ ] corporate-DAO Requirements Specification
- [ ] corporate-DAO Solution Specification
- [ ] corporate-DAO Business Model Specification
- [ ] corporate-DAO Pitch-Deck
- [x] corporate-DAO Pitch-Video
- [ ] corporate-DAO Website: The public part of the dedicated Website
- [x] Design Thinking PoC under involvement of a pilot customer

### Additional Deliverables
- [ ] links to GitHub and to MIRO 
- [x] Draft of a list of experts
